baseURL = "https://mikewiegand.github.io/machineweaver-blog/"
languageCode = "en-us"
title = "MachineWeaver"
enableRobotsTXT = true

[params]
  tagline = "Notes from a Generative Engineer."
  author = "Michael Wiegand"
  description = "AI-driven code generation, OTA systems, PackWeave, LangGraph, and the Thor stack."
  showReadingTime = true
  comments = false

  [params.giscus]
    enabled = false

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[permalinks]
  posts = "/posts/:year/:month/:day/:slug/"

[pagination]
  pagerSize = 10
